### ISSUE TITLE
Layout of german "token settings" looks crowded

### ISSUE THREAD

**Issue by Razortide** [arnonram/swade-npc-importer#104]
Hello @arnonram,

I just found, that the token settings window is a bit too small. "Vision Radius" overlaps with "Dämmrig" which is bigger then "Dim" :-)

Maybe you could give a bit more space there?

Best regards,
Marc

**Comment by arnonram** [comment]
![image](https://user-images.githubusercontent.com/43678762/160178488-70b4448d-3443-4415-9fff-b0ccccb995d5.png)

**Comment by Razortide** [comment]
Interestingly, I do have a linebreak between Vision Radius and the fields to enter the value in the import view:
![image](https://user-images.githubusercontent.com/35796457/161399871-1edc09bd-8636-4cac-a7df-3b366e584649.png)

The Token Settings view looks great, but Vision Radius translation is not applied here, see #106
