### ISSUE TITLE
German importer lacks Special abilities and weapons

### ISSUE THREAD

**Issue by Razortide** [arnonram/swade-npc-importer#105]
Hello @arnonram, I just did a dry run with a few characters and found I missed something:

Stier: Size is not imported, as well as weapons.
Zombie: Neither Weapons nor Special Abilities are imported.
I tried with another character, weapons are missing, however, talents were imported.

I will shoot you another statblock for that :-)

**Comment by arnonram** [comment]
@Razortide i cannot seem to reproduce this.

In the sample blocks you sent me (bull, zombie) special abilities are imported as weapons  or size etc..
