### ISSUE TITLE
Untranslated parts in German

### ISSUE THREAD

**Issue by Razortide** [arnonram/swade-npc-importer#106]
NPC Importer "Main Screen": The selection lists are not imported:
1. Actors type is NPC, Character not NSC and Charakter
2. Wild Card is Yes / No instead of Ja / Nein
3. Disposition is Hostile/Neutral/Friendly instead of Feindlich/Neutral/Freundlich
4. Vision Radius does not have a translation expression in de.json
5. Degrees (360 if empty) does not have a translation expression in de.json (btw. there is a typo. It is degress, instead of degrees)

Actor already exists:
Import with different name exists in de.json but is not applied.

**Comment by arnonram** [comment]
English was actually hardcoded in here... so no translation at all..

I've added the following lines to `eng.json`

```json
  "npcImporter.HTML.Yes": "Yes",
  "npcImporter.HTML.No": "No",
  "npcImporter.HTML.VisionRadius": "Vision Radius",
  "npcImporter.HTML.VisionAngleLable": "Degrees (360 if empty)",
```

**Comment by arnonram** [comment]
@Razortide i can add to the German with google translate, but i see you already have another pull request ready, so why don't you add them to the `de.json` file

**Comment by Razortide** [comment]
Hello @arnonram,

added strings to the PR as suggested.

Best regards,
Marc

**Comment by Razortide** [comment]
Hey @arnonram,
I found a few missing strings: 

- "Paste statblock here ONLY if you're using Firefox or are over http..." -> Import screen
- "Select Compendiums" -> Headline in the Compendium Selection screen
- Vision Radius (German string not applied in Token settings menu)

**Comment by arnonram** [comment]
@Razortide good catch. Thanks

**Comment by Razortide** [comment]
Inserted the discussed strings in to de.json. See #109
