### ISSUE TITLE
stat blocks from Tyrnador PDFs are not imported correctly

### ISSUE THREAD

**Issue by jja006** [arnonram/swade-npc-importer#111]
I'm trying to import stat blocks from the Tyrnador: Secrets of Tyland PDF, but the format of these blocks is causing special abilities to be placed in the wrong locations.

I am attaching a sample stat block that I copied out of the PDF, and a screen-shot of the results when importing that block using the module. Note this example shows at least one issue, but I've encountered a few different issues with stat blocks from this book, so probably a few format changes will be needed.

I'd like to learn what changes are necessary to these stat blocks to  get them to import more cleanly; I'm hoping I can then do some find/replace changes to the bulk of them so I can get them in.

Is there a reference copy of a full stat block that matches the format the module expects? I think if I could see some working examples I might be able to work out what the issues are with Gramel's blocks and at least help to come up with a fix.

Thanks.

[BlackOcopus.txt](https://github.com/arnonram/swade-npc-importer/files/8791339/BlackOcopus.txt)
.
![ScreenShot](https://user-images.githubusercontent.com/453433/170830732-12fcdb38-a3e1-4794-a420-bff683509dd0.jpg)

**Comment by SalieriC** [comment]
First try adding a colon `:` after `Special Abilities` That's likely to solve a whole lot of your problems.

**Comment by jja006** [comment]
*slaps forehead*
That's literally all it was for most of the issues! Thanks so much for taking the time to point that out, you've saved me a lot of frustration with this.

I'll close the issue. Also I want to leave this here in case anyone else has a similar question; once I realized those colons were sometimes missing, I also found that some special abilities on some of the blocks were missing the leading bullet-point (seems to happen a lot with spec. ability Armor +x for some reason).

**Comment by jja006** [comment]
Ensuring the colon delimiter is present on the Special Ability heading, and that bullet-points are present for each special ability solved the bulk of the occurrences. This is just an issue with frequent editing mistakes in the stat blocks included in the Tyrnador PDF(s).

**Comment by jja006** [comment]
Ensuring the colon delimiter is present on the Special Ability heading, and that bullet-points are present for each special ability solved the bulk of the occurrences. This is just an issue with frequent editing mistakes in the stat blocks included in the Tyrnador PDF(s).

**Comment by SalieriC** [comment]
A missing colon is an all too common problem with stat blocks. It is indeed so common, that I made a regex rule to fix that for me. ^^
Anyway, you're welcome. =)
