### ISSUE TITLE
Ability type items don't apply AEs to the actor when imported.

### ISSUE THREAD

**Issue by SalieriC** [arnonram/swade-npc-importer#113]
Similar to #94, this doesn't seem to work on ability type items. Haven't tested that for flags.

**Comment by arnonram** [comment]
I believe this is related to how i imported Effects which was not good

i know what i did wrong and i think i fixed it this time around

**Comment by SalieriC** [comment]
AEs on Actors using the importer will now carry any AEs but the AE won't be applied to the actor itself. (as discussed on Discord)
