### ISSUE TITLE
`equipped` changed to `equipStatus` in SWADE v 1.2.x 

### ISSUE THREAD

**Issue by SalieriC** [arnonram/swade-npc-importer#124]
SWADE v. 1.2.x changed the `equipped` property on items of type `gear`, `shield`, `weapon` and `armor` to `equipStatus`. Four lines in itemBuilder.js need to be changed to respect these changes.

`equipStatus` uses numbers to identify the status, these are as follows:
**Weapons:**
Stored = 0; Carried = 1; Off-Hand = 2; Main Hand = 4; Two Hands = 5
**All other:**
Stored = 0; Carried = 1; Equipped = 3

I suggest changing 
- [x] line [320](https://github.com/arnonram/swade-npc-importer/blob/ea93a6f7c317dc09f67d5803be05037d12e41f42/scripts/dataBuilders/itemBuilder.js#L320) to `equipStatus: 1`,
- [x] line [298](https://github.com/arnonram/swade-npc-importer/blob/ea93a6f7c317dc09f67d5803be05037d12e41f42/scripts/dataBuilders/itemBuilder.js#L298) to `equipStatus: 3`,
- [x] line [272](https://github.com/arnonram/swade-npc-importer/blob/ea93a6f7c317dc09f67d5803be05037d12e41f42/scripts/dataBuilders/itemBuilder.js#L272) to `equipStatus: 3` and
- [x] line [238](https://github.com/arnonram/swade-npc-importer/blob/ea93a6f7c317dc09f67d5803be05037d12e41f42/scripts/dataBuilders/itemBuilder.js#L238) to `4` or `5`, depending on the stat block (if the weapon mentions "2-hands" or "2H" or "two-handed" or "Parry -1"*)

`*` This part is tricky as not all stat blocks - especially the ones from PEG - specifically state if a weapon is two-handed. This makes it a guessing game. But since weapons which are carried in both hands usually incur a parry penalty it is fair to assume that weapons which state that are used with two hands. It's not so easy with things like Staves or Spears but should work in many cases.

**Comment by arnonram** [comment]
for weapons: two hands can also be in the description but not mandatory, as for example: bastard sword, falchion, etc..

**Comment by SalieriC** [comment]
Maybe default to 2-H in these cases unless another weapon or shield is on the stat-block?

**Comment by arnonram** [comment]
if we start going down that road, it'll be overly complicated i think...

so i think the options are:
- if two hands appear then => `equipStatus: 5`
- if not then => `equipStatus: 4`

keeps it clean and simple

**Comment by arnonram** [comment]
Instead of trying to come up with every possibility of how it can be written, i went with the user config route

![image](https://user-images.githubusercontent.com/43678762/198408247-b714a894-ba62-41de-a1cc-f3dec44c80f5.png)
