### ISSUE TITLE
Error when clicking the import button or opening settings.

### ISSUE THREAD

**Issue by kristianserrano** [arnonram/swade-npc-importer#125]
Getting the following error when clicking the button in the Actor directory.
![Screen Shot 2022-09-16 at 4 19 59 PM](https://user-images.githubusercontent.com/1796189/190726403-ccb9aa2d-9fe0-4caf-bee7-44cb33e0c241.png)

I also get an error when clicking Configure Settings
![Screen Shot 2022-09-16 at 4 22 17 PM](https://user-images.githubusercontent.com/1796189/190726586-fde4f45d-dc41-4207-8a64-d60648f820ff.png)

**Comment by arnonram** [comment]
seems also a v10 issue
