### ISSUE TITLE
Consider renaming the module SWADE Stat Block Importer

### ISSUE THREAD

**Issue by kristianserrano** [arnonram/swade-npc-importer#127]
NPC Importer is a bit of a misnomer since it imports characters as well. The major feature is importing Savage Worlds stat blocks. Thus, I think SWADE Stat Block Importer might draw more attention and present a clearer understanding of what the module does.

**Comment by arnonram** [comment]
yeah, been thinking about this since second or third version,  but starting to change names after people already know it seemed bad to me

I agree that the name is better...

**Comment by arnonram** [comment]
i'll do it with the v10 compatibility, along with a minor version bump to 0.2.0

**Comment by kristianserrano** [comment]
That makes sense.
