### ISSUE TITLE
Better way to import Special Abilities

### ISSUE THREAD

**Issue by SalieriC** [arnonram/swade-npc-importer#13]
Most creatures have Special abilities that mention their names instead of the generic text. This is when the Importer doesn't use predefined Special Abilities and creates them on the fly.
I propose the following:
If "Use modified Special Abilities" is set to true in the configuration either:
- Only check those by name and ignore the text (everything after the colon),
- or preferably check the predefined oney by name, add those to the actor and then edit the imported ones by adding the given text of the Special Ability on top of its description followed by a horizontal line (![image](https://user-images.githubusercontent.com/1230041/102209831-a6a74880-3ed1-11eb-8414-bf122f0a550f.png)).

Both methods would ensure that the general description is there and any icons and Active Effects set for those abilities. The second method would also be foolproof because then specific descriptions that make things clearer would also be imported. In any case the importer should be configurable to ignore things like adding additional wounds (i.e. Resilient) or adding ignored wounds (i.e. Undead) in order to not conflict with predefined Active Effects that can do that.

Additionally Size cannot be properly set up as a predefined Edge or Hindrance because it is usually called "Size (+x)" or "Size (-x)". It would be a great improvement if the module would then look for a predefined Edge/Hindrance called "Size", and adds the value on its own behind the name after using the predefined one.

**Comment by arnonram** [comment]
so several issue here actually:

1. **Get _original_ special abilities text**: The second option is better in my opinion, and quite simple to implement.
2. **Additional/Ignore Wounds**: adding two boolean settings for these two options
3. **Size**: I belive Armor should probably behave the same.

**Comment by arnonram** [comment]
**part 1:**
![image](https://user-images.githubusercontent.com/43678762/102548202-f8fb8b80-40c2-11eb-91c9-141f2f517cad.png)

**Comment by arnonram** [comment]
@SalieriC 

**re: additional wounds**  => At the moment extra wounds is affected by Size,  if wildcard, and Resilient (actually adding resilient support now).

do you think the additional wounds should be ignored for all these traits?

**Comment by SalieriC** [comment]
@arnonram: Looking good, but shouldn't it do that for everything? Because you can have on virtually anything diffferent descriptions and the the predefined one does not get imported. Also there are other things that add +x to the title, maybe you want to cover these as well (Flying, Aquatic, Burrow, ...). Then there are Weaknesses and Immunities that add other stuff in parenthesis, good grief this is madness. Maybe a somewhat universal way of handling this can be done? Like:
- If "<Edge/Hindrance> (anything): <Description>"
- look for <Edge/Hindrance>
- Add (anything) to title if there is a match
- Add <Description> to Description if there is a match
- Or crerate "<Edge/Hindrance> (anything)" with <Description> if there is no match.

Also I'd leave no empty space below the horizontal line but that's just me. ^^

**Additional Wounds:** That's a difficult topic. I'd say it should be optional. But also maybe it should be just documented that importing stuff with Active Effects is dumb and shouldn't be done. I know that it was **me** who requested it but on second thought, I can't justify that. Also it creates more problems like: "What exactly do I need to set up with Active Effects?"

**Comment by arnonram** [comment]
re: edges/Hindrances -> yeah, the generic way you suggest is pretty much what I did, so it's basically adding a list of any of these that might have additional info... But as you say, it's a big list that can alway get larger..

re Additional Wounds -> it is tricky... I'm wondering how they'll do it on the premium content (to which I'll have to sort of adapt, or add options)

**Comment by SalieriC** [comment]
What I also noticed: If "Use modified Special Abilities" is enabled, there is no need to paste them to the description I think.
