### ISSUE TITLE
Add Bennie default number for NPCs

### ISSUE THREAD

**Issue by JasonSunday** [arnonram/swade-npc-importer#130]
I would like to be able to set the default number of Bennies for NPCs so that when play Pathfinder for Savage Worlds, so that NPC Wild Cards have 3 Bennies by default instead of 2.

**Comment by arnonram** [comment]
not that familiar with Savage PF, so is that to any NPC or just NPC Wild Cards?

I could add a new settings for num of bennies for NPC Wild Cards, with a default of 2, which can be changed
