### ISSUE TITLE
Importing "`/`-powers" fails.

### ISSUE THREAD

**Issue by SalieriC** [arnonram/swade-npc-importer#132]
Dual-Powers (or whatever they are called) fail to import properly. I've tested this with Boost/Lower Trait only for now but it may be true for any other power having a `/` in the name. They are imported as two separate powers and are not retrieved from a compendium.

**Comment by arnonram** [comment]
merged into [v0.2.4](https://github.com/arnonram/swade-npc-importer/releases/tag/v0.2.4)
