### ISSUE TITLE
Failed to build finalActor error

### ISSUE THREAD

**Issue by ScottSilLew** [arnonram/swade-npc-importer#133]
Hi,

When I try copy and paste a stat block into the text field and click the button to complete it, the window closes and no actor shows up in the expected folder. I looked at the log and it says "Failed to build finalActor: ReferenceError: isEmpty is not defined" on line 29 in global.js. 

I'm using this block to test:

Agent
Employed by the shadowy Agency, US Agents investigate espionage and supernatural incidents.

Attributes: Agility d8, Smarts d8, Spirit d6, Strength d6, Vigor d6
Skills: Academics d6, Athletics d6, Common Knowledge d6, Fighting d6, Notice d8, Occult d6, Persuasion d6, Research d6, Shooting d8, Stealth d8, Survival d4
Pace: 6; Parry: 5; Toughness: 5
Edges: Agent, Guts, Level Headed, Rock and Roll!
Hindrances: Cautious, Vow (Major-Destroy or contain the supernatural)
Gear: Gatling pistol (Range 12/24/48, Damage 2d6, RoF 3, AP 1), disguise kit, Agency badge.

**Comment by arnonram** [comment]
Hi @ScottSilLew ,

I couldn't reproduce it locally, 

I learned from chatting with others, that the PDF software used might raise some issue as well...

Are you copying from PDF? If you copy the stat-block from your issue here (meaning, not directly from pdf) and try to import does it still fail?


Also, can you please specify: 
- foundry version
- swade version
- module version
- browser

**Comment by ScottSilLew** [comment]
Hi @arnonram,

I'm using: 
Foundry version 9 build 280.
Swade version 1.2.5
Module Version .2.1

I'm the game master, so I'm using the local Foundry browser.
I think I recall a patch note for Foundry saying that "isEmpty" was deprecated, but I could be wrong. It might have also been that isEmpty replaces something else.

**Comment by arnonram** [comment]
Hi Scott,

Those are some old versions you got there (foundry & swade), which version
0.2.x do not support.

So sorry 😔

Any reason why you are not updating?

**Comment by ScottSilLew** [comment]
Yes, but I forget why. I think there was another module that I deemed necessary. I'll try to update and see what happens.

**Comment by ScottSilLew** [comment]
Actually, this isn't the same issue, but it seems like it creates duplicate entries for skills and edges, for some reason. I can create a new issue, if needed.
