### ISSUE TITLE
Request for Module Update for Foundry VTT v11

### ISSUE THREAD

**Issue by brunocalado** [arnonram/swade-npc-importer#134]
I hope this message finds you well. I have been using your module for Foundry VTT and it has been a valuable asset to my gaming experience. I wanted to reach out and kindly request an update for your module to be compatible with Foundry VTT version 11.

Thank you for considering this request. I understand that updates require time and effort, and I truly appreciate your dedication to improving the module.

**Comment by arnonram** [comment]
@brunocalado glad you are finding this module useful :)

i'll see about updating it. Life is hectic a bit at the moment, so will need to see how much effort it'll be...

**Comment by LeRatierBretonnien** [comment]
Merge request pushed, with v11 support + French support
