### ISSUE TITLE
Imported flavour text cannot have line breaks.

### ISSUE THREAD

**Issue by SalieriC** [arnonram/swade-npc-importer#15]
The imported flavour text has always the line breaks removed. If possible the module should import line breaks in the flavour text.

**Comment by arnonram** [comment]
Never thought this would be a problem since usually, the description is one paragraph, but if it's two then they'll be joined.

But sure...

**Comment by SalieriC** [comment]
Take a look at the Gremlin from the new Deadlands for example. Many from 50F as well. =)

**Comment by SalieriC** [comment]
On second thought, this should only apply if the option for @h, @e, etc. is checked, because then it can be assumed the player already worked on the stat block. If not the flavour text will have line breaks all over the place because of the way PDFs work regarding formatting.

**Comment by arnonram** [comment]
the bio/description and the special abilities are parsed separately and then joined later, so there is no problems there

**Comment by arnonram** [comment]
I tried leaving all the lines breaks and it looked ugly as hell....

I came up with a solution that should work well enough: 
- If the line ends with a period followed by a line-break, then I leave it with a line break, otherwise, I remove the line break.
