### ISSUE TITLE
A way to configure all the Prototype Token properties upon import

### ISSUE THREAD

**Issue by SalieriC** [arnonram/swade-npc-importer#16]
It would greatly reduce prep time if there was a way to configure all properties of the Prototype Token upon import, except maybe the image and of course position.
This is especially true for Vision and Bars. There should be - if possible - a standard setup in the modules config and in the import dialogue.

**Comment by arnonram** [comment]
Currently, there are default, hard-coded values for (some) vision settings and configurable for disposition. I was planning on moving those to the settings sections.

But the Prototype Token has lots of settings, I would rather not replicate them all, and rather have a distilled list, maybe something along the line of:

- Has Vision
- Dim Vision
- Bright Vision
- Resources (all)
- Disposition (already implemented)

**Comment by SalieriC** [comment]
I would like to add Display Name as well as I find that quite important.

**Comment by arnonram** [comment]
implemented in a new sub-menu of the module's configuration:

- Has Vision
- Dim Vision
- Bright Vision
- Token Disposition
- Display Name
