### ISSUE TITLE
Not detecting Portuguese translation

### ISSUE THREAD

**Issue by lipefl** [arnonram/swade-npc-importer#17]
The module is not detecting the language "Português (Brasil)".
I think the problem is that the correct file name for Portuguese (Brazil) should be "pt-BR.json", most modules use it that way.

**Comment by arnonram** [comment]
Ohh... OK, i'll look into it

I was going by the documentation which says to use [ISO 639-2](https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes) for languages and did not find the Brazilian Português in it...
