### ISSUE TITLE
special abilities

### ISSUE THREAD

**Issue by montver** [arnonram/swade-npc-importer#19]
if the NPC has special abilities like  Armor +2 o tou: Star vampires have thick hide.  In spanish not implemented in the sheet. I don't know if it works in english the armour isn't a string like "npcImporter.parser.Toughness" : "Dureza",
is possible that if you include an string with: "npcImporter.parser.armour" : "Armadura"  
It works if you include it??

**Comment by arnonram** [comment]
I think this might be the same issue as [this one](https://github.com/arnonram/swade-npc-importer/issues/21)

I was comparing lowercase to non-lowercase armor (so Armor to armor) which of course came back false... not sure how it got through :(

**Comment by arnonram** [comment]
but this led me to a bug that I was not adding the Toughness  bonus (from undead, for example)
