### ISSUE TITLE
In the special abilities Speed becomes a weapon and Bite ignores Strenght

### ISSUE THREAD

**Issue by DanieleSuppo** [arnonram/swade-npc-importer#22]
Not sure how to solve this, but when you import the following stat block, because Speed has a d10 is converted also in a weapon.

Not sure if you want to create a Dict of Special abilities that use the dice but are not weapons.
Also (at least in my italian settings) the bite is converted into d6 and not Strenght + 1d6

CYBER HOUND
Cyber hounds were a wildly successful
attempt to graft cybernetics on animals.
The hounds retain the loyalty typical to dogs
and possess a number of enhancements, such as
infrared sensors, steel jaws, cybernetic legs, and a
reinforced exoskeleton, that grant them durability,
speed, and night vision, as well as a powerful bite.
Some cyber hounds come with communication
devices used to alert their owners when an
intrusion occurs. Due to their capabilities and the
cost to add cybernetics to a dog, they are quite
expensive.
Attributes: Agility d8, Smarts d6 (A), Spirit d8,
Strength d8, Vigor d10
Skills: Athletics d8, Fighting d8, Notice d10
Pace: 8; Parry: 6; Toughness: 9 (2)
Edges: Alertness, Fleet-Footed
Special Abilities:
• Armor +2: Armor plating.
• Bite: Str+d6.
• Low Light Vision: Cyber hounds ignore penalties for Dim and Dark Illumination.
• Infravision: Cyberhounds can ‘see’ by
detecting heat, halving penalties for poor
lighting when attacking targets that radiate
warmth.
• Speed: d10 running die.
• Targeting Computer: The cyberhound has
a +2 bonus to Notice rolls to detect living
creatures and a +2 bonus to Fighting rolls

**Comment by arnonram** [comment]
@DanieleSuppo is it possible you've are on v0.1.2?

- I solved the **speed** issue in v0.1.3 ([see issue](https://github.com/arnonram/swade-npc-importer/issues/6)) by specifically excluding it from the weaponBuilder
- re: **Bite** -> cannot reproduce it on my end. Could you perhaps open Developers Console while foundry is open, run the import again, and then copy all the console log that start with `SWADE NPC Importer |` (paste it into the filter). You can attach the file to the issue

![image](https://user-images.githubusercontent.com/43678762/102414545-63e38e80-3fff-11eb-9e3c-6c2a1d3e5045.png)

**Comment by DanieleSuppo** [comment]
I double checked the version and it's 0.1.3:

![image](https://user-images.githubusercontent.com/2264815/102464200-59031b00-404c-11eb-99a4-33007cb3a0b2.png)

Today I will debug and provide you more details on both issues.
The strenght one is 99.9% related to the language, but I will write as much details as I can collect.

**Comment by arnonram** [comment]
I believe i found the **Speed** issue: stupid case-sensitivity... in English the localization was lower case and in Spanish upper-case
