### ISSUE TITLE
d6 instead of 1d6 breaks the system

### ISSUE THREAD

**Issue by DanieleSuppo** [arnonram/swade-npc-importer#23]
Last one for today :)

For some reason SWADE or Better rolls or Foundry, they don't like when you write in the Damage d6 instead of 1d6 so I guess you need to always "filter" the dice to be sure they have a 1 in front if they do not match the pattern of "(number)d(number)"
So d6 should become 1d6, etc..

Same stat importer to test (it happens with Bite and Speed, because of Issue #22 ):

CYBER HOUND 
Cyber hounds were a wildly successful 
attempt to graft cybernetics on animals. 
The hounds retain the loyalty typical to dogs 
and possess a number of enhancements, such as 
infrared sensors, steel jaws, cybernetic legs, and a 
reinforced exoskeleton, that grant them durability, 
speed, and night vision, as well as a powerful bite. 
Some cyber hounds come with communication 
devices used to alert their owners when an 
intrusion occurs. Due to their capabilities and the 
cost to add cybernetics to a dog, they are quite 
expensive.
Attributes: Agility d8, Smarts d6 (A), Spirit d8, 
Strength d8, Vigor d10
Skills: Athletics d8, Fighting d8, Notice d10
Pace: 8; Parry: 6; Toughness: 9 (2)
Edges: Alertness, Fleet-Footed
Special Abilities:
• Armor +2: Armor plating.
• Bite: Str+d6.
• Low Light Vision: Cyber hounds ignore penalties for Dim and Dark Illumination.
• Infravision: Cyberhounds can ‘see’ by 
detecting heat, halving penalties for poor 
lighting when attacking targets that radiate 
warmth.
• Speed: d10 running die.
• Targeting Computer: The cyberhound has 
a +2 bonus to Notice rolls to detect living 
creatures and a +2 bonus to Fighting rolls

**Comment by arnonram** [comment]
This is a [foundry Issue](https://discord.com/channels/170995199584108546/784244473261588480/788132162754183190) that has a hotfix

**Comment by DanieleSuppo** [comment]
great, so I'm gonna close this issue
