### ISSUE TITLE
Not working in linux systems

### ISSUE THREAD

**Issue by parvusdomus** [arnonram/swade-npc-importer#24]
So the thing is my computer is linux (mint) and regardless of the pdf reader I use (tried with evince, acrobat 9, acrobat dc...) some NPCs can't be imported. I can import the lich but can't import the dragon, zombie or cat (for example). I have tried both in english and spanish using the official SWADE manual for each language and I always get a statblock error.

Trying to do the same in a windows 10 system always work for the same npcs (tried with adobe dc and google chrome).

**Comment by arnonram** [comment]
That's... strange. My first suspect world be the reader, but your tried several, and it sometimes work... 

I'll see if I can get around to debugging this on a Linux vm to figure it out

**Comment by parvusdomus** [comment]
Thanks for checking it, a VM should be enough to replicate it. I suspect a linux vs windows encoding issue.

**Comment by arnonram** [comment]
Tested again on Linux (ubuntu) and seems to work as expected
