### ISSUE TITLE
Various small issues in 0.1.4

### ISSUE THREAD

**Issue by SalieriC** [arnonram/swade-npc-importer#28]
From testing v,0.1.4:
- Gear sometimes gets imported with a "," behind, usually when three pieces of gear are in the stat block, the second gets the comma.
- "Power Points:" in the main stat block aren't recognised.
- Fear/Fearless are both taken from compendiums as fearless due to fuzzy search. (Edit: This does not happen when only one of it is present.) (Edit 2: It does not always happen apparently. This becomes stranger by the minute...) (Edit3: Aite, I think I got this: It imports it as Fear and Fearless but upon opening Fear, that becomes Fearless right away. Also neither of the two can be deleted right away. If the user tries it won't disappear but will be gone after refreshing.)
- Fuzzy search fails however at importing weapons (and others?), i.e. if the Stat Block calls for a "Gatling Pistol" the "Gatling Pistol (.36) won't get imported (here a fuzzy search would actually be beneficial).
- Weapons don't have their damage updated. This realistically only matters with natural weapons like claws and might be edited by the user instead. 
- Size does not get updated correctly on the sheet. It'll just make the data.stats.size empty. (Edit: And Wounds are not added properly depending on Size as well.)
- Line breaks in description work weird but this might be intentional.
- Hyphens are considered as a divider when importing gear, causing it to parse as two different items as in "stone-headed ax (Str+d6)" becomes "Stone" (gear) and "-headed Ax" (weapon).
- Hyphens mess up with capital letters in name. So "This-Is-An-Actors-Name" becomes: "This-is-an-actors-name".
- The importer has problems importing things as set up by the user. Example: If there is a Weapon and an Edge called "Claws" and the user sets the stat block up as "@w Claws: ..." it might import the Edge instead of the Weapon. (Edit: Same is true for powers and edges in the list of powers (example: Monstrous Ab. Fear and Power _fear_.))
- Fleet-Footed does not increase the running die. 

I will update this issue when I find new issues.

**Comment by SalieriC** [comment]
Update: "Hyphens are considered as a divider when importing gear, causing it to parse as two different items as in "stone-headed ax (Str+d6)" becomes "Stone" (gear) and "-headed Ax" (weapon)."

**Comment by SalieriC** [comment]
Update 2:
- The importer has problems importing things as set up by the user. Example: If there is a Weapon and an Edge called "Claws" and the user sets the stat block up as "@w Claws: ..." it might import the Edge instead of the Weapon.

Also another note on the Fear/Fearless problem.

**Comment by SalieriC** [comment]
Update 3:
Added another note regarding not properly recognising the needed item type.

**Comment by arnonram** [comment]
phew... so only one left here is:
==> Weapons don't have their damage updated.

**Comment by arnonram** [comment]
natural weapons done. 

Check if natural weapon (one of Claw, Bite, Horns) and if found in Compendium, sets it's damage to the one supplied (overriding the compendium damage)
