### ISSUE TITLE
Edges with stuff in Parenthesis are not properly imported.

### ISSUE THREAD

**Issue by SalieriC** [arnonram/swade-npc-importer#33]
Example: When importing Arcane Background (Chi Master) it imports Arcane Background (Black Magic) (as B come before C I suppose) instead, renaming it. Possibly due to fuzzy search method.

**Comment by arnonram** [comment]
well shit..

This is due to me actually trying to search properly when something has parenthesis, for example 
- Languauge (Russian)
- Quirk (picking nose)
- Connections (Media)

i guess I'll have to add an exception for AB
