### ISSUE TITLE
Powers in spanish

### ISSUE THREAD

**Issue by montver** [arnonram/swade-npc-importer#34]
I found a bug in powers in spanish, i don't know if happens in english. Normally if the character has an arcane background in the sheet appears the slider of powers. But when i parsed don't succeed, and don't appers the powers.

**Comment by arnonram** [comment]
@montver  can you post here an example of an Arcane Background edge name in Spanish?

**Comment by montver** [comment]
Mago (TA)
Mentalista (TA)
Inventor (TA)
...
