### ISSUE TITLE
Import fails for certain stat blocks

### ISSUE THREAD

**Issue by eXaminator** [arnonram/swade-npc-importer#35]
Hi, I am having trouble importing an actor from ETU: Argyll the Dog.

First I thought it broke due to some special abilities, but even without them the import breaks.

Here is a the Statblock I'M trying to import:
```
ARGYLL
Attributes: Agility d6, Smarts d6 (A), Spirit
d8, Strength d4, Vigor d8
Skills: Fighting d4, Notice d8, Stealth d8
Pace: 6; Parry: 4; Toughness: 4
```

This is the error I'm getting: 
```
SWADE NPC Importer | Failed to build finalActor: TypeError: Cannot read property 'value' of undefined
```

**Comment by eXaminator** [comment]
After playing around some more, I **think** this happens if a statblock is missing a description block between the name and the attributes.

**Comment by SalieriC** [comment]
I can confirm this. Happens only if no description is given as far as I can tell.
For context: 
![image](https://user-images.githubusercontent.com/1230041/103292524-41ce1100-49ee-11eb-9762-c2e9530a5e3f.png)

**Comment by arnonram** [comment]
yep... i know where i screwed up :-/
