### ISSUE TITLE
Hide module for non GMs

### ISSUE THREAD

**Issue by eXaminator** [arnonram/swade-npc-importer#37]
Currently the module seems to be accessible for all players, but I think it should only be accessible for GMs.

Why is this a problem?

1. Players might not have the neccessary rights to create actors
2. Players might not have access to all needed compendiums / items (this leads to an error message which is displayed everytime a player loads foundry)

**Comment by SalieriC** [comment]
It could be tied to the permissions. Players can indeed have permission to create actors. It might should only show the button to those who have permission to create actors.

**Comment by arnonram** [comment]
Hmm... OK, that's a good point.

I always thought it would be nice to allow players to be able to import as well, but forgot about permission to create character/npc, or access to modules ...

Actually never tried to log-in as a player and see how the Importer behaves  (badly, as it happens).

I like @SalieriC idea to add it to players with permissions, but I'll also see if I can add a setting that will allow the GM to decide **if** the IMport button will appear to players with permissions...

---
### Todo:
-  If player does not have permission to create character/npc then hide the Import Button
- add setting option to GM to hide/reveal Import button to players (that have permission)

**Comment by arnonram** [comment]
> If player does not have permission to create character/npc then hide the Import Button
Done

> add setting option to GM to hide/reveal Import button to players (that have permission)
I'll break it off to another issue... maybe I'll add it sometime
