### ISSUE TITLE
Change Parse language

### ISSUE THREAD

**Issue by arnonram** [arnonram/swade-npc-importer#4]
Once we have localization, we want to be able to parse statblocks in any language we set. So that if a user running Foundry in Sapnish, for example, wants to import an English statblock, they'll be able to

**Comment by lipefl** [comment]
Would the importer work with a portuguese statblock if i provide you with a portuguese (ptbr) translation file? Anyway, i'd like to contribute with this. Im not very familiar with github yet tough, can i send the file here?
Nice work, btw!

**Comment by arnonram** [comment]
@lipefl 
That's the idea. I want the user to be able to choose (from the Settings page) what language the statsblock is and for the module to use the appropriate language.

I'd be happy for any translation help 😄 ... Grab the file [here ](https://github.com/arnonram/swade-npc-importer/blob/main/lang/en.json) and translate the right-side part (after the colon `:`)

If you could provide me with a sample file in Portuguese, that'll be excellent.

**Comment by lipefl** [comment]
Nice! Here are the files
Translation:
https://www.dropbox.com/s/svhq15d8t7le4to/ptbr.json?dl=0

Bull stats in ptbr (copied from the portuguese swade book):
https://www.dropbox.com/s/z0bn4fu69mh609u/bull-ptbr.txt?dl=0
