### ISSUE TITLE
Issues with parsing additional fields

### ISSUE THREAD

**Issue by eXaminator** [arnonram/swade-npc-importer#40]
I have a few issues when parsing statblocks with additional fields, in this example specifically Charisma.

I have added "Charisma:" to the list of additional fields.

I am using this statblock as an example:
```
Some Guy
Some description
Attributes: Agility d4, Smarts d6, Spirit d8,
Strength d8, Vigor d8
Skills: Fighting d8
Charisma: –1; Pace: 5; Parry: 7; Toughness:
9
```

Here are some of the problems I noticed:
- If the additional stat is set to type "number", negatives will be ignored (probably because the minus is not just a simple "dash" caracter).
- If the additional stat is set to type "string" it will include the semicolon after the value ("–1;")
- The additional stat (Charisma) will be displayed in the NPC sheet, but if I open the "tweaks" dialog for the character, the checkbox for Charisma will not be shown as selected.

**Comment by eXaminator** [comment]
The last issue (albeit not a big one) still seems unresolved. Just wanted to document this here, thanks for the other fixes!

> The additional stat (Charisma) will be displayed in the NPC sheet, but if I open the "tweaks" dialog for the character, the checkbox for Charisma will not be shown as selected.

**Comment by arnonram** [comment]
Strange..  I'll take a look
