### ISSUE TITLE
Not working on browsers

### ISSUE THREAD

**Issue by lipefl** [arnonram/swade-npc-importer#42]
On browsers it gets an error when trying to parse.
Chrome, Edge: TypeError: Cannot read property 'readText' of undefined
Firefox: Uncaught (in promise) TypeError: navigator.clipboard is undefined

Btw, it's an awesome tool! Congratulations!

**Comment by arnonram** [comment]
that's strange, most browsers support this (apart from IE)

What versions of those browsers are you using?

![image](https://user-images.githubusercontent.com/43678762/104731656-b5895100-5744-11eb-9417-7fd8a57b1f93.png)

**Comment by lipefl** [comment]
All of them with the most recent version. I tried again today (even with Chrome Anonymous). 

If you say it's working for you, no problem, it must be something on my end.

**Comment by arnonram** [comment]
Did it get the error and stop, or parses anyway and imports the actor?

**Comment by lipefl** [comment]
It stops. Windows 10.

**Comment by arnonram** [comment]
And is it consistent on all stat blocks?

The failure is in reading from the clipboard..

**Comment by lipefl** [comment]
I think it's not even reading the copied text. Here's a print from the console.

![image](https://user-images.githubusercontent.com/10639148/104740486-c3c87480-5726-11eb-982f-f21e18deb95a.png)

**Comment by arnonram** [comment]
Very strange...

I'll sniff around...

**Comment by arnonram** [comment]
I think i found the reason==> https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined

I found it when I tried to use the Importer on hosted foundry instance I have on my raspberry pi. I did not enable HTTPS and got the same error... perhaps later today or tomorrow I'll change the hosted foundry to run on HTTPS and test it

**Comment by arnonram** [comment]
@lipefl another way for this to work:

1. Go to chrome://flags/#unsafely-treat-insecure-origin-as-secure
2. enable it
3. add your URL of your foundry host (for example: `http://myhost:30000`)
