### ISSUE TITLE
Bug: Speacial Abilities Headline is put into Description after importing a modified block

### ISSUE THREAD

**Issue by SalieriC** [arnonram/swade-npc-importer#45]
When a modified block is imported, Special abilities are set mostly correct (apart from a few bugs seen in other issues) but the Headline is still put into the description:
![image](https://user-images.githubusercontent.com/1230041/103945340-5a989e00-5135-11eb-88fa-f54000ec150f.png)
With no content below, the headline does not need to be present, neither does the vertival line.

**Comment by arnonram** [comment]
Caught that one... already fixed for next release :)
