### ISSUE TITLE
Allow importing special abilities as gear

### ISSUE THREAD

**Issue by eXaminator** [arnonram/swade-npc-importer#51]
Ok, this sounds strange, but hear me out on this!

Right now, Special Abilities are added to the description text. But I would really like to use the description block for the actual description of an NPC. Right now even the imported description from the stat block pushes down all the special abilities, far away from any quick access to them if the description contains more than a sentence or two.

I propose to add a setting that imports "unknown" special abilities as "Gear" item entries instead of adding them to the description, with the description (and potential Link) of that ability in the items description text.

The reason being, that Gear creates a nice entry on the NPC sheet which can be expanded to read the description.

I know this is a workaround, but so is the description field or any solution until the system hopefully adds actual support for special abilities in the future.

In addition, there should be an option to mark special abilities as gear when using the extended "@" syntax.

**Comment by SalieriC** [comment]
So basically all you're asking is to add @g for gear? Everything else you ask for is already there if you just edit the bullet point to be @w or @a. Or do you want it to behave like this by default on not edited stat blocks? I don't know if that would be worth an option as it seems a little special. But @arnonram must be the judge on that.

**Comment by eXaminator** [comment]
> So basically all you're asking is to add @g for gear?

I would much prefer a setting to set this as the default for "unmatched" abilities (those that are not recognized as edge/weapon etc.). I don't use the special syntax because copying directly from a PDF is the main reason I use this module ;) And having the extra step of needing to edit the statblock in a text editor at least reduces the value for me. The `@g` is what I meant with my last sentence. But that would preferably be in addition to a setting that allows me to define this as the default behavior.

> I don't know if that would be worth an option as it seems a little special.

Well, so is "misusing" the description field. I just want to be able to choose my own poison here :) The Description is also something that can potentially be shown to players, and I don't want my players to see that their ETU room mate is actually a demon with certain special abilities... (just an example).

This also has the added advantage, that the actual ability description can be hidden until you need it. So it takes up much less space overall.

**Comment by arnonram** [comment]
@eXaminator

With the new **Ability** item in swade system 0.17.0, i think this one could be closed

**Comment by eXaminator** [comment]
I agree.
