### ISSUE TITLE
Burrow does not use predefined items

### ISSUE THREAD

**Issue by SalieriC** [arnonram/swade-npc-importer#52]
Same as #32 before; `Burrow (15")` for example creates a new item when using the `@` syntax instead of using the predefined item.

**Comment by SalieriC** [comment]
Same is true for `Weakness (anything)`.

**Comment by arnonram** [comment]
Can you give me an example of how this looks in the statblock?

**Comment by arnonram** [comment]
by "_predefined_" item, you mean the premium content item?

**Comment by SalieriC** [comment]
@arnonram 
See Giant Worm in SWADE (p.184):
>  Burrow (20″): Giant worms tunnel through 
> the ground, blocked only by solid bedrock.

By "predefined" I mean an edge that I've set up for the Special Ability that should be used from a compendium when using `@e`.

**Comment by SalieriC** [comment]
Same is true for Poison (modifier).
