### ISSUE TITLE
Special Ability importing

### ISSUE THREAD

**Issue by SalieriC** [arnonram/swade-npc-importer#56]
SWADE 0.17.0 and above now has an ability item type. I'd suggest the following:
The importer should import everything under the `Special Abilities:` line as abilities to the sheet unless it is weapons or armour which should be imported as such. Also it would be great if it would use its current search method to import abilities (and Special Ability armour and weapons) if the GM has set them up in a compendium. This was a great feature all the time and shouldn't be lost now.
If a special ability mentions Power Points and one or more powers it should give the ability the `Grants Powers` property and import the Power Points and powers (from a compendium again if already set up) as well.

This module always was a really great thing and including these features would make it incredibly awesome because it would most likely remove all the work one would had to take setting up all the `@h`, `@w`, `@e`, etc.

**Comment by arnonram** [comment]
So this is basically done, but i not going to deal with importing specific powers.

the Importer will search special abilities for mention of Power Points, parse out the number before it (ie 50 Power Points), and set the character with it
