### ISSUE TITLE
! in Edge names causes the Edge to not be found.

### ISSUE THREAD

**Issue by SalieriC** [arnonram/swade-npc-importer#60]
Edges like "Hold the Line!" and "Rock and Roll!" are not recognised because the importer seems to ignore the `!` and then creates an Edge without the `!`.

**Comment by SalieriC** [comment]
Same is true for `-` i.e. in "Two-Fisted".

**Comment by arnonram** [comment]
> Two-Fisted
 and such are working for me 

edges with `!` are fixed now
