### ISSUE TITLE
SWADE Importer does not work | PrototypeToken field displayName field failed provided validation rule

### ISSUE THREAD

**Issue by Razortide** [arnonram/swade-npc-importer#61]
Hello Arnon, 

as discussed over chat: With version 0.1.17 I am unable to create characters. I receive the following errors:

![2021-05-04_08h27_07](https://user-images.githubusercontent.com/35796457/116968063-07ce8d80-acb4-11eb-9682-6e0c354154ea.jpg)
![2021-05-04_08h27_19](https://user-images.githubusercontent.com/35796457/116968065-08672400-acb4-11eb-8ca5-9090afd76dcd.jpg)
[parsed-output.txt](https://github.com/arnonram/swade-npc-importer/files/6419340/parsed-output.txt)

I tried three different profiles and failed with all of them.

Also: You have a log typo: "prased data" instead of "parsed data" also see screenshot :-)

**Comment by Razortide** [comment]
I just downloaded v0.1.16 and could reproduce the error. v0.1.15 is working fine.

**Comment by arnonram** [comment]
@Razortide I can't seem to reproduce this on my envs

1. Can you supply: OS, browser, Foundry version, and SW Ruleset version?
2. Can you disable other modules and see it the error reproduces?

For my part I've tested on my windows and raspberry Pi 
![image](https://user-images.githubusercontent.com/43678762/117203549-d19a2680-adf7-11eb-95a6-a17100f66f6c.png)

**Comment by Razortide** [comment]
@arnonram, I will check tomorrow the module approach, but what I can already provide is this:

Browser Edge
OS Raspbian
Foundry 0.7.9
SWADE 0.8.X (either .2 or .3)

I guess the .X version does not go well with the 0.1.16+, but this is just a hunch.

**Comment by Razortide** [comment]
Hm... seems to be tied to my world apparently :-( It works fine on new worlds and worlds with modules activated. But just not on my world (even if I only have the Importer active)
