### ISSUE TITLE
Unable to parse this Statblock

### ISSUE THREAD

**Issue by Razortide** [arnonram/swade-npc-importer#65]
Hello Arnon,

I tried importing this statblock but failed. I don't receive an error but I see something in the log:

![image](https://user-images.githubusercontent.com/35796457/117305720-51b79f00-ae7f-11eb-8457-9e7429542efc.png)
[parsing-result.txt](https://github.com/arnonram/swade-npc-importer/files/6434828/parsing-result.txt)
[statblock.txt](https://github.com/arnonram/swade-npc-importer/files/6434834/statblock.txt)

Apparently, this entry caused the issue for me:
 Vanish: When nimerigar are startled,
they can vanish as a free action. This
works like the teleport power, but uses
Spirit as the arcane skill, costs no Power
Points, and can’t be modified.

**Comment by Razortide** [comment]
(size hasn't been taken over as well)

**Comment by arnonram** [comment]
so many ways to make a minus sign... sigh... 
will fix this

**Comment by arnonram** [comment]
two bugs in one :)

got the buggers

**Comment by Razortide** [comment]
Thank you!
