### ISSUE TITLE
When assigning Special Abilities as weapons, Trait is sometimes missing.

### ISSUE THREAD

**Issue by Razortide** [arnonram/swade-npc-importer#66]
More often then not, when creating weapons out of special abilities, it will leave the Trait empty:

![image](https://user-images.githubusercontent.com/35796457/117317067-7749a600-ae89-11eb-9d2f-c876dd3ea616.png)

This does not go well with the Better Rolls 2 module which looks for this.

Suggestion:

If there is no Range given (e.g. 12/24/48) Fighting should be automatically taken.

**Comment by arnonram** [comment]
@Razortide 
but for ranged weapons it can be either Shooting of Athletics...

I'll have no way to distinguish between those. So i can make Shooting the default of Ranged weapons, and the user will need to change it manually..

**Comment by Razortide** [comment]
Interesting thought. You are totally right. Or you could just set fighting, because that is the one thing that is defined at least 90%?
