### ISSUE TITLE
Certain Stat Block format required?

### ISSUE THREAD

**Issue by gravagehulk** [arnonram/swade-npc-importer#67]
I have tried several stat blocks and nothing seems to work. When I select my options and click "import", nothing happens. There's no error message or anything. It just does nothing. Is there a certain format it's looking for? For example, I copied the following stat block to my clipboard:

Veva Nagle
Archetype: Indian Shaman Race: Human (PC) (F)

Attributes: Agility d6, Smarts d8, Spirt d8, Strength d6, Vigor d6

Parry 5, Toughness 5, Pace 6+d6

Skills: Athletics d6, Common Knowledge d6, Faith d4, Fighting d6, Notice d8, Occult d8, Persuasion d8, Research d4, Riding d8, Shooting d6, Stealth d8, Survival d8

Edges: Arcane Background (Shaman), Bolster, Brave

Hindrances: Backlash (Shaman), Loyal, Lyin’ Eyes, Old Ways Oath (major)

Features: Arcane Background

Personality: Cuddly, Reluctant

Shaman: Power Points 15, Powers: Arcane Protection [Peace Pipe => Cold], Confusion [Talisman => Sound]

Gear: Bow: Range 12/24/48, Damage 2d6, RoF 1, Spear: Str+d6, Parry +1, Reach 1, Native shield (small): +1 Parry, –1 Cover, Min Str d4, Hardness 7, Tomahawk: Str+d6, Horse, Tomahawk: Str+d6, Horse, Lance: Str+d6, Reach 2

I also tried this:

Novice Human

Attributes: Agility d4, Smarts d4, Spirit d4, Strength d4, Vigor d4
Skills: Athletics d4, Common Knowledge d4, Language (Native) d8, Notice d4, Persuasion d4, Stealth d4
Pace: 6; Parry: 2; Toughness: 4
Weapons: Unarmed (Range Melee, Damage Str)
Language: Native (native, d8)
Current Wealth: $500
Current Load: 0 (21)

Edit: I take it back. I am getting the following error. I'm still not sure what format it's looking for:

![image](https://user-images.githubusercontent.com/69117052/118503239-107d8580-b6f0-11eb-8d80-769fd1a6ab5e.png)

Another test. This stat block was taken directly out of a SWADE book and it doesn't work either. I'm confused as to what I have to do to get this to work.

Attributes: Agility d8, Smarts d6, Spirit d8, Strength d6, Vigor d6
Skills: Athletics d4, Common Knowledge d4, Driving d4, Fighting d8, Intimidation d6, Language (English d6), Language (Russian d8), Notice d6, Persuasion d8, Research d6, Shooting d8, Spellcasting d8, Stealth d8, Taunt d8, Thievery d6
Pace: 6; Parry: 8; Toughness: 5
Hindrances: Loyal (To family and friends), Outsider
(Russian), Vengeful (Minor)
Edges: Arcane Background (Magic), Block (Imp), Combat Reflexes, Strong Willed, Streetwise
Powers: Bolt, deflection, quickness. Power Points: 10 Gear: 9mm pistol (Range 12/24/48, Damage 2d6, RoF 1,
AP 1), 2 extra clips, switchblade.

**Comment by arnonram** [comment]
Hi @gravagehulk, i'm guessing you are running your running Funrdy self-hosted and on HTTP...

Please see the head of the readme note (i should probably make it clearer by adding this error as an example):

> Please Note: If you are running Foundry as self-hosted, and with the HTTP protocol, then the Importer will not be able to read the data from the clipboard (this is security related stuff). Either set your hosted Foundry to work with HTTPS, or set the` Insecure origins treated as secure` flag in your browser (or equivalent) appropriately. ([see here](https://github.com/arnonram/swade-npc-importer/issues/42#issuecomment-773385058))

**Comment by gravagehulk** [comment]
Yeah, I JUST figured it out. I used to run my games exclusively out of the client, so this isn't something I ever would have been able to address. I just made the appropriate modification to my browser and it seems to be working now. Thanks for the quick response. You can close this.
