### ISSUE TITLE
Enhancement: Set data.data.bennies.max and .value to 0 on import

### ISSUE THREAD

**Issue by SalieriC** [arnonram/swade-npc-importer#74]
The system is very bad at handling NPCs of non-Wild Card status as it does not touch the Bennies. Setting `data.data.bennies.max` and `data.data.bennies.value` to 0 if a non-Wild Card NPC is imported would be great to fix what the system misses.
This is a minor enhancement. Not of priority but a QoL improvement. It might be out of scope for this module though, not on me to decide.

**Comment by arnonram** [comment]
That's not to tough to implement

So it should be something like this:
- NPC & not Wild Card = 0/0
- NPC & Wild Card = 2/2
- Character & not Wild Card = ?/?
- Character & Wild Card = 3/3

**Comment by arnonram** [comment]
Actually, that's not taking into account edges/hindrances that affect bennies... :/

**Comment by arnonram** [comment]
i'll just ignore edges/hindrances that affect bennies at the moment...

**Comment by SalieriC** [comment]
There are no non-Wild Card characters but other than that yes.
