### ISSUE TITLE
Feature request: Better search for gear.

### ISSUE THREAD

**Issue by SalieriC** [arnonram/swade-npc-importer#86]
I know this is a somewhat problematic thing to do but would it be possible to enhance the search method for gear? For example: Stat blocks often list something like `Great sword (Str+...)` under gear. In compendiums however it is often better to use something like `Sword, great` for better sorting. Currently the importer doesn't recognise this and thus creates the item instead of using an item from the compendium. Editing the stat block is also not an option as comma is used to seperate items, so the importer isn't able to tell which comma is used for separation and which as part of a name.
What I think could work would be to identify each word like so (pseudo code warning):
```
let name = gearName;
let words = [];
for (eachWord in name) {
  words.push(eachWord);
}
if (itemInCompendium.name.includes(words[0]) && itemInCompendium.name.includes(words[1]) ...) {
  //use itemInCompendium
} else {
  //create item
}
```
The goal is to minimise errors due to fuzzy search while still being able to find at least most of the desired gear.

**Comment by arnonram** [comment]
That's a good idea

Another option would be to crate an array of the name (split on comma),
sort it alphabetically, and compare...

Not sure what would be more effective

**Comment by arnonram** [comment]
this should work with the new release
