### ISSUE TITLE
Foundry v9 support

### ISSUE THREAD

**Issue by eXaminator** [arnonram/swade-npc-importer#87]
Hi,

it seems this module is lacing proper v9 support.

I'm trying to import the following statblock and get the following error:

```
Some Name
Some description
Attributes: Agility d6, Smarts d6, Spirit d8,
Strength d6, Vigor d6
Skills: Faith d8, Fighting d4, Occult d8, Notice d6, Stealth d6
Pace: 6; Parry: 4; Toughness: 5
Hindrances: Vengeful (Minor)
```

```
SWADE NPC Importer | Failed to import: Error: PrototypeTokenData dimSight "0" must be a non-negative number
```

It doesn't seem to matter what I enter into the dim sight field. I guess some change in Foundry now casts this value to be a string but you expect an integer or something like that?

**Comment by arnonram** [comment]
@eXaminator hi,
Yes I've seen it when I updated, and actually already have as fix... Just need some more testing before releasing :)
