### ISSUE TITLE
Import fails due to sightAngle being "NaN".

### ISSUE THREAD

**Issue by SalieriC** [arnonram/swade-npc-importer#88]
The `Vision Angle` setting should default to `0`, instead it is empty, which results in failed imports if not otherwise configured. It should have a default assigned to it by the importer so that new users can still import even if they have not changed the settings.

**Comment by arnonram** [comment]
it actually does have a default, but it's not being picked up,.. hmm..

**Comment by arnonram** [comment]
not sure why it's not taking the default, but i've added some description text, and if the field is empty, then the it'll be set to 360
![image](https://user-images.githubusercontent.com/43678762/152528132-7276fe04-feb1-414a-b31e-b1baf9ece984.png)
