### ISSUE TITLE
Nameless items are created... again.

### ISSUE THREAD

**Issue by SalieriC** [arnonram/swade-npc-importer#91]
When importing actors it can happen that items are created, that do not have a name. This is a critical bug as it can cause compendium merges to fail and - in combination with compendium folders - destroy compendiums beyond repair. It also only becomes apparent when merging actor in a compendium which makes it even more dangerous, because by the time you merge, chances are you can't easily find the affected actor.
![image](https://user-images.githubusercontent.com/1230041/152499187-efa2a304-21eb-44d6-a09d-84264b06ab31.png)

Feel free to DM me on Discord, I can probably find a stat block on which this happened to me.

**Comment by SalieriC** [comment]
When testing, I just realised, that you can spot this error on importing as well, if you leave the console open:
![image](https://user-images.githubusercontent.com/1230041/152500586-519e8ed0-f0fa-4ba4-8286-efb4af4dc6e7.png)

I also have a stat block on which it happens now.

**Comment by arnonram** [comment]
occurred due to splitting on colon (in `parseStatBlock.js`) when we had an unexpected colon (more than one).
this wrecked a bit of havoc on the system.
