### ISSUE TITLE
Imported items from compendium doesn't copy flags and AEs.

### ISSUE THREAD

**Issue by SalieriC** [arnonram/swade-npc-importer#94]
Possibly because the importer uses some data from the item in the compendium but not all properties?

**Comment by arnonram** [comment]
Yea, sort of ... Didn't occur to me if might be useful

Shouldn't be to difficult to add

**Comment by SalieriC** [comment]
it's especially useful when AEs are important, like added Toughness on a Ring of Protection or whatever. Flags are important in case of other modules like Automated Animations which stores all its vfx and sfx as flags on the item.
