### ISSUE TITLE
"Has vision" is always set to true on import.

### ISSUE THREAD

**Issue by SalieriC** [arnonram/swade-npc-importer#95]
No matter if left unchecked on import or not.

**Comment by arnonram** [comment]
Strange, I was just checking that.

Is those latest version?

**Comment by SalieriC** [comment]
Yeah, on the previous version it was working fine. 🙈

**Comment by arnonram** [comment]
ugh... i guess having a version without regression is like having eggs without bacon ...

**Comment by SalieriC** [comment]
On the plus side: I was really impressed with how fast the importer became in the current version compared to the previous one. 👍 
And also so far I have not noticed that using special abilities from compendiums stopped working which was a bug in like every version after one that fixed it. :D

**Comment by arnonram** [comment]
re: speed. Great! That was the main reason for this latest version

re: vision. I  think it's Foundry bug. I can definitely see that i send `vision:false`, but get back `vision: true` ... need to dig a bit deeper

**Comment by arnonram** [comment]
@SalieriC  it's a SWADE system thingy => https://gitlab.com/peginc/swade/-/issues/463
