### ISSUE TITLE
Problems importing existing items from compendiums.

### ISSUE THREAD

**Issue by SalieriC** [arnonram/swade-npc-importer#96]
Sorry to break this to you, but there is regression again on this one. 🙈 
It's Size this time and maybe others I have yet to find. Encountered this with `Small –2` this time.

**Comment by arnonram** [comment]
You mean `Size -2` ? Small -2 is not a valid 

I cannot reproduce it, can you send me a stat bloc (here or via discord)?

**Comment by SalieriC** [comment]
Ehem... Nevermind me, Terribly sorry. 🙈
